### ISSUE TITLE
adding file to Github repository

### ISSUE THREAD

**Issue by victoriatodd2** [jonnyhtw/weather-types#1]
Would it be possible to add the file referenced in f=open(path + 'from-james/cluster_means.txt') to the Github repository? 
Thank you!

**Comment by jonnyhtw** [comment]
Hi there, 

I'm looking into this now. This data was sent to me rather than being generated by me so I am investigating sharing options.

Cheers, 

Jonny

**Comment by jonnyhtw** [comment]
Code merged. Closing. 🥳

**Comment by victoriatodd2** [comment]
Thank you so much!
