### ISSUE TITLE
Identifying daily synoptic types

### ISSUE THREAD

**Issue by victoriatodd2** [jonnyhtw/weather-types#4]
Hi, I am trying to use this code to identify synoptic types twice daily to look at inidividual storm event days over NZ. Is there any way to identify the kidson types of the calculated EOFs when the EOFs are as few as two?

**Comment by jonnyhtw** [comment]
sorry i only just saw this notification. i'll have a look asap

**Comment by jonnyhtw** [comment]
> Hi, I am trying to use this code to identify synoptic types twice daily to look at inidividual storm event days over NZ. Is there any way to identify the kidson types of the calculated EOFs when the EOFs are as few as two?

hi victoria, thank you for your patience here!! 😃 

the method used in this work is completely general and would work for only 2 eofs. we chose 5 eofs and 12 clusters since this was what was used in the original work by kidson.
